# Generated by Django 3.0 on 2021-07-16 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0005_auto_20210716_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='db_apis',
            old_name='last_bady_method',
            new_name='last_body_method',
        ),
    ]
